version: '3.8'

# Single node Cassandra for testing with limited resources

services:
  cassandra-1:
    image: cassandra:5.0
    container_name: bulk-cassandra-1
    hostname: cassandra-1
    environment:
      - CASSANDRA_CLUSTER_NAME=BulkOpsCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_NUM_TOKENS=256
      - MAX_HEAP_SIZE=1G
      - JVM_OPTS=-XX:+UseG1GC -XX:G1RSetUpdatingPauseTimePercent=5 -XX:MaxGCPauseMillis=300

    ports:
      - "9042:9042"
    volumes:
      - cassandra1-data:/var/lib/cassandra

    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

    healthcheck:
      test: ["CMD-SHELL", "nodetool info | grep -q 'Native Transport active: true' && cqlsh -e 'SELECT now() FROM system.local'"]
      interval: 30s
      timeout: 10s
      retries: 15
      start_period: 90s

    networks:
      - cassandra-net

networks:
  cassandra-net:
    driver: bridge

volumes:
  cassandra1-data:
    driver: local
