name: PR CI

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.gitignore'
      - 'LICENSE'
  workflow_dispatch:

jobs:
  async-cassandra:
    uses: ./.github/workflows/ci-monorepo.yml
    with:
      package: async-cassandra
      run-integration-tests: false
      run-full-suite: false

  async-cassandra-bulk:
    uses: ./.github/workflows/ci-monorepo.yml
    with:
      package: async-cassandra-bulk
      run-integration-tests: false
      run-full-suite: false
